[project]
name = "geekhouse"
version = "0.1.0"
description = "A smart house with LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.40.0",
    "mpremote>=1.24.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
