# WiFi Configuration
[wifi]
ssid = "Your WiFi SSID"
password = "Your WiFi Password"

# Server Configuration
[server]
port = 80

# LED Configuration
[leds.1]
pin = 2
color = "yellow"
location = "roof"
type = "led"

[leds.2]
pin = 3
color = "white"
location = "garden"
type = "led"

# Sensor Configuration
[sensors.1]
pin = 1
type = "water"
location = "roof"
unit = "level"
adc = true

[sensors.1.config]
type = "linear"
params = { m = 1.0, b = 0.0 }

[sensors.2]
pin = 0
type = "light"
location = "roof"
unit = "lux"
adc = true

[sensors.2.config]
type = "polynomial"
params = { coefficients = [0.0, 0.1] }


[sensors.3]
pin = 26
type = "light"
location = "garden"
unit = "lux"
adc = true

[sensors.3.config]
type = "polynomial"
params = { coefficients = [0.0, 0.1] }

[sensors.4]
pin = 4
type = "temperature"
location = "internal"
unit = "celsius"
adc = true

[sensors.4.config]
type = "linear"
params = { m = -0.02926, b = 437.2 }
