Output geekhouse.gif
Output geekhouse.mp4
Set CursorBlink true
Set FontSize 16
Set Width 800
Set Height 800
Set TypingSpeed 50ms

Type python ../src/llm_iot/dialogue.py
Enter
Wait+Line />>>/
Type "Get LEDs"
Enter
Wait+Line />>>/
Sleep 2s
Type "What is the temperature?"
Enter
Wait+Line />>>/
Sleep 2s
Type "Turn on the yellow LED"
Enter
Wait+Line />>>/
Sleep 2s
Type "Turn on the LED in the garden"
Enter
Wait+Line />>>/
Sleep 2s
Type "What's the light level on the roof?"
Enter
Wait+Line />>>/
Sleep 2s
Type "What is the water level?"
Enter
Wait+Line />>>/
Sleep 2s
Type "Turn off the white LED"
Enter
Wait+Line />>>/
Sleep 2s
Type "Turn off the LED on the roof"
Enter
Wait+Line />>>/
Sleep 5s
Type "quit"
Enter
